[versions]
agp = "8.10.0"
coreSplashscreen = "1.2.0"
coreTesting = "2.2.0"
espressoContrib = "3.7.0"
gson = "2.13.2"
hamcrest = "3.0"
hiltAndroidTesting = "2.57.2"
hiltAndroidVersion = "2.57.2"
hiltWorkVersion = "1.3.0"
kotlin = "2.2.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
kotlinxCoroutinesAndroid = "1.10.2"
lifecycleViewmodelKtx = "2.9.4"
loggingInterceptor = "5.1.0"
material = "1.13.0"
activity = "1.11.0"
constraintlayout = "2.2.1"
mockk = "1.14.5"
navigationTesting = "2.9.5"
numberPicker = "2.4.13"
retrofit = "2.9.0"                  # stable version
room_version = "2.8.1"
runner = "1.7.0"
truth = "1.4.5"
turbine = "1.2.1"
testCore = "1.7.0"
workRuntimeKtx = "2.10.5"
navigationFragmentKtx = "2.9.5"
navigationUiKtx = "2.9.5"
lifecycleService = "2.9.4"
places = "5.0.0"
navigation = "2.9.5"
fragment = "1.8.9"
espressoIdlingResource = "3.7.0"
monitor = "1.8.0"
uiautomator = "2.3.0"


[libraries]

# ----------------------------
# Android Core Libraries
# ----------------------------
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-fragment = { group = "androidx.fragment", name = "fragment", version.ref = "fragment" }
androidx-fragment-testing = { module = "androidx.fragment:fragment-testing", version.ref = "fragment" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "material" }


# ----------------------------
# Lifecycle & ViewModel
# ----------------------------
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-lifecycle-service = { group = "androidx.lifecycle", name = "lifecycle-service", version.ref = "lifecycleService" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-lifecycle-compiler = { module = "androidx.lifecycle:lifecycle-compiler", version.ref = "lifecycleViewmodelKtx" }

# ----------------------------
# Navigation
# ----------------------------
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
androidx-navigation-testing = { module = "androidx.navigation:navigation-testing", version.ref = "navigationTesting" }

# ----------------------------
# Coroutines
# ----------------------------
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesAndroid" }

# ----------------------------
# Room (Database)
# ----------------------------
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room_version" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref="room_version" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room_version" }

# ----------------------------
# Retrofit & Network
# ----------------------------
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }

# ----------------------------
# Google Places API
# ----------------------------
places = { module = "com.google.android.libraries.places:places", version.ref = "places" }

# ----------------------------
# UI NumPicker Utilities
# ----------------------------
number-picker = { module = "io.github.ShawnLin013:number-picker", version.ref = "numberPicker" }

# ----------------------------
# WorkManager
# ----------------------------
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }

# ----------------------------
# Hilt (DI)
# ----------------------------
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroidVersion" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroidVersion" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hiltAndroidTesting" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltAndroidTesting" }

androidx-hilt-work-v110 = { module = "androidx.hilt:hilt-work", version.ref = "hiltWorkVersion" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltWorkVersion" }



# ---------------------------------
# Testing - JUnit & Instrumentation
# ---------------------------------
junit = { group = "junit", name = "junit", version.ref = "junit" } # JUnit 4 – for local unit testing
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" } # AndroidX JUnit – instrumentation testing support

# ------------------------------------------------
# Testing - Core Andoid JUnit Instrumented
# ------------------------------------------------
androidx-test-core-ktx = { module = "androidx.test:core-ktx", version.ref = "testCore" }

# ----------------------------
# Testing - Test Runner & Rules
# ----------------------------
androidx-test-runner = { module = "androidx.test:runner", version.ref = "runner" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "runner" }

# ----------------------------
# Testing - Mocking
# ----------------------------
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }


# ----------------------------
# Testing - Espresso
# ----------------------------
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "espressoContrib" }
androidx-espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "espressoContrib" }


# ----------------------------
# Testing - Kotlin Flow Utilities
# ----------------------------
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }   # Testing utilities for Kotlin Flow/StateFlow

# ----------------------------
# Testing - Assertions
# ----------------------------
truth = { module = "com.google.truth:truth", version.ref = "truth" }          # Fluent assertions for better readability
hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest" }    # Matcher library for writing flexible assertions

# ----------------------------
# Testing - Hilt + Lifecycle
# ----------------------------
androidx-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "coreTesting" }
androidx-espresso-idling-resource = { group = "androidx.test.espresso", name = "espresso-idling-resource", version.ref = "espressoIdlingResource" }
androidx-monitor = { group = "androidx.test", name = "monitor", version.ref = "monitor" }
androidx-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }



[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hiltPlugin = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroidVersion"}
navigationSafeArgs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }

